"use strict";

//一些类型的合集
var NODE_TYPE = {
  NODE_TYPE_RECT: 1,
  NODE_TYPE_DIAMOND: 2,
  NODE_TYPE_ANNULAR: 4,
  NODE_TYPE_CIRCLE: 5,
  NODE_TYPE_TOPIC: 6,
  NODE_TYPE_ELLIPSE: 7
}

var EDGE_TYPE = {
  EDGE_TYPE_FLOW: -1,
  EDGE_TYPE_SOLID: 1,//实线
  EDGE_TYPE_DASHWITHSINGLEALLOW: 0,
  EDGE_TYPE_DASHWITHDOUBLEALLOW: 2,
}

var ELEMENT_TYPE = {
  ELEMENT_TYPE_UNKNOWN: 0,
  ELEMENT_TYPE_NODE: 1,
  ELEMENT_TYPE_EDGE: 2,
  ELEMENT_TYPE_POLYGON: 3
}

var OBJECT_TYPE = {
  TYPE_ENTITY: 1,
  TYPE_LINK: 2
}

module.exports = {
  NodeType: NODE_TYPE,
  EdgeType: EDGE_TYPE,
  ElementType: ELEMENT_TYPE,
  ObjectType: OBJECT_TYPE
}
